services:
  clash:
    image: ghcr.io/sqing33/clash:latest
    container_name: clash
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 1m
    volumes:
      - /root/data/clash/config.yaml:/root/.config/clash/config.yaml # config.yaml 在 Windows 版 clash 目录的 profiles 下 获取
    ports:
      - "7888:8080"
      - "7890:7890"
# 设置宿主机代理
# sudo nano  /etc/profile.d/proxy.sh

# 添加内容
# export http_proxy="http://127.0.0.1:7890/"
# export https_proxy="http://127.0.0.1:7890/"
# export no_proxy="127.0.0.1,localhost"

# 设置执行权限
# sudo chmod +x  /etc/profile.d/proxy.sh

# 应用代理设置
# source /etc/profile.d/proxy.sh
