services:
  immich:
    image: ghcr.io/sqing33/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DB_HOSTNAME=10.0.0.10
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=10.0.0.10
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - MACHINE_LEARNING_HOST=0.0.0.0
      - MACHINE_LEARNING_PORT=3003
      - MACHINE_LEARNING_WORKERS=1
      - MACHINE_LEARNING_WORKER_TIMEOUT=120
    volumes:
      - /root/data/immich:/config
      - /nas/photos/upload:/photos  # 包含所有上传至 Immich 的照片
      - /nas/photos:/libraries #optional  # 存储在 Immich 外的的文件夹
      - /nas:/nas
    ports:
      - 12380:8080
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    image: ghcr.io/immich-app/immich-machine-learning:release-openvino
    extends:
      # hwaccel.ml.yml下载地址：https://github.com/immich-app/immich/releases/latest/download/hwaccel.ml.yml
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /home/sqing/DockerData/immich/model-cache:/cache

    restart: always
    healthcheck:
      disable: false
      
  redis:
    image: docker.io/redis:6.2-alpine
    ports:
      - "6379:6379"
    container_name: redis
    restart: always

  postgres14:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - "5432:5432"
    container_name: postgres14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /root/data/immich/db:/var/lib/postgresql/data
