version: '3.8'

services:
  immich:
    image: ghcr.io/sqing33/immich:latest
        container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=192.168.5.66
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.5.66
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - MACHINE_LEARNING_HOST=0.0.0.0
      - MACHINE_LEARNING_PORT=3003
      - MACHINE_LEARNING_WORKERS=1
      - MACHINE_LEARNING_WORKER_TIMEOUT=120
    volumes:
      - /root/data/immich:/config
      - /nas/photos/upload:/photos  # 包含所有上传至 Immich 的照片
      - /nas/photos:/libraries #optional  # 存储在 Immich 外的的文件夹
    ports:
      - 12380:8080
    restart: always

  redis:
    image: ghcr.io/sqing33/redis:latest
    ports:
      - "6379:6379"
    container_name: redis
    restart: always

  postgres14:
    image: ghcr.io/sqing33/postgres:14
    ports:
      - "5432:5432"
    container_name: postgres14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /root/data/immich/db:/var/lib/postgresql/data
