version: "3.8"
services:
  jackett:
    image: ghcr.io/sqing33/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /root/data/jackett:/config
      - /nas/downloads:/downloads
    ports:
      - 9117:9117
    restart: always
