services:
  mongodb:
    container_name: mongodb
    image: ghcr.io/sqing33/mongodb
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /root/data/jmalcloud/mongodb/data/db:/data/db
      - /root/data/jmalcloud/mongodb/backup:/dump
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: --wiredTigerCacheSizeGB 0.5

  jmalcloud:
    container_name: jmalcloud
    image: ghcr.io/sqing33/jmalcloud
    environment:
      MONGODB_URI: "mongodb://mongo:27017/jmalcloud"
      TZ: "Asia/Shanghai"
      JVM_OPTS: "-Xms256m -Xmx1024m"
    volumes:
      - /root/data/jmalcloud/files:/jmalcloud/files/
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: ghcr.io/sqing33/nginx
    ports:
      - 7070:80
      - 7071:8089
    environment:
      TZ: "Asia/Shanghai"
    links:
      - jmalcloud
      - office
    restart: unless-stopped
