version: '3.8'

services:
  jupyter-notebook:
    image: ghcr.nju.edu.cn/sqing33/jupyter-notebook
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - /root/code:/home/jovyan/work # 挂载本地目录到容器内的工作目录
    restart: always
