version: "3.8"

services:
  mongodb:
    image: ghcr.io/sqing33/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    ports:
      - "27017:27017"
