services:
  mrdoc:
    image: docker pull ghcr.nju.edu.cn/sqing33/mrdoc:v9.1	
    container_name: mrdoc
    ports:
      - "7086:10086"
    volumes:
      - /root/data/MrDocPro:/app/MrDoc
    restart: always
