version: '3.8'
services:
  nginx-proxy-manager-zh:
    container_name: nginx-proxy-manager-zh
    image: ghcr.nju.edu.cn/sqing33/nginx-proxy-manager-zh
    restart: always
    ports:
      - '11180:80'
      - '11181:81'
      - '11443:443'
    volumes:
      - /root/data/nginx-proxy-manager:/data
      - /root/data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    environment:
      INITIAL_ADMIN_EMAIL: root
      INITIAL_ADMIN_PASSWORD: 12346578
