# 启动前需要先创建Nginx外部挂载的配置文件（ /root/nginx/conf/nginx.conf,当服务器和容器都不存在 nginx.conf 文件时, 执行启动命令的时候 docker会将nginx.conf 作为目录创建）

# 创建挂载目录
# mkdir -p /root/data/nginx/conf
# mkdir -p /root/data/nginx/log
# mkdir -p /root/data/nginx/html

# 生成容器并复制配置文件和HTML内容到宿主机
# docker run --name nginx -p 888:80 -d swr.cn-south-1.myhuaweicloud.com/docker-sqing-huawei/nginx:nginx
# docker cp nginx:/etc/nginx/nginx.conf /root/data/nginx/conf/nginx.conf
# docker cp nginx:/etc/nginx/conf.d /root/data/nginx/conf/conf.d
# docker cp nginx:/usr/share/nginx/html /root/data/nginx/
    
# 删除nginx容器
# docker rm -f nginx

# 重新创建容器
version: '3.8'
 
services:
  nginx:
    image: ghcr.nju.edu.cn/sqing33/nginx
    container_name: nginx 
    ports:
      - "888:80"
    volumes:
      - /root/data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf 
      - /root/data/nginx/conf/conf.d:/etc/nginx/conf.d 
      - /root/data/nginx/log:/logvar/nginx 
      - /root/data/nginx/html:/usr/share/nginx/html 
    restart: always 


 
