services:
  photoview:
    image: ghcr.io/sqing33/photoview
    hostname: photoview
    container_name: photoview
    restart: always
    ports:
      - 4875:80

    environment:
      PHOTOVIEW_DATABASE_DRIVER: sqlite
      MARIADB_PASSWORD: 12345678
      PHOTOVIEW_MEDIA_CACHE: /home/photoview/photo_cache
      PHOTOVIEW_SQLITE_PATH: /home/photoview/photoview.db
    volumes:
      - /etc/localtime:/etc/localtime:ro ## 使用主机的本地时间
      - /etc/timezone:/etc/timezone:ro  ## 使用主机的时区
      - /root/data/photoview:/home/photoview
      - /nas:/nas
