version: "3.8"

services:
  qbittorrent:
    image: ghcr.nju.edu.cn/sqing33/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - "18080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - /root/data/qbittorrent:/config
      - /nas/downloads:/downloads
    restart: unless-stopped
