version: "3.8" # 定义版本

services:
  resilio-sync:
    image: ghcr.io/sqing33/resilio-sync
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /root/data/resilio-sync/config:/config
      - /nas/sync/downloads:/downloads
      - /nas/sync:/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: always
