services:
  transmission:
    image: ghcr.nju.edu.cn/sqing33/transmission	
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /root/data/transmission:/config
      - /nas/downloads:/downloads
      - /root/data/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
