version: '3'
services:
  verysync:
    image: ghcr.nju.edu.cn/sqing33/verysync
    container_name: verysync
    restart: always
    volumes:
      - /nas/sync:/data
    ports:
      - "13000:3000"
      - "22037:22037/udp"
      - "22027:22027/udp"
      - "8886:8886"

