services:
  dpanel:
    image: swr.cn-south-1.myhuaweicloud.com/docker-sqing-huawei/dpanel:dpanel
    container_name: dpanel
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8807:8080"
    environment:
      - APP_NAME=dpanel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
